name: thriveers
description: "ThrivEers - Comprehensive Autism Therapy Management Platform for mobile and web"
publish_to: "none" # Private package

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Core UI & Navigation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  sizer: ^2.0.15
  flutter_svg: ^2.0.10+1

  # Firebase Services
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_database: ^12.0.0

  # State Management
  provider: ^6.1.2

  # Data & Analytics
  fl_chart: ^0.69.2

  # Media & Files
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2

  # Storage & Persistence
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5

  # Audio & Recording
  record: ^6.0.0

  # Utilities
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  # Custom Fonts (if needed in the future)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
