// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDleVP1qj0BFeWnNGiTtF3Jz_FhMUC3Gtw',
    appId: '1:569573804437:web:19ac93dbac59fd24880e9c',
    messagingSenderId: '569573804437',
    projectId: 'ablnew-9f930',
    authDomain: 'ablnew-9f930.firebaseapp.com',
    storageBucket: 'ablnew-9f930.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVD_pTd2_OOUcJtmvL8bsTdd26qX5lNM',
    appId: '1:569573804437:android:1ad0940dbe6b26c6880e9c',
    messagingSenderId: '569573804437',
    projectId: 'ablnew-9f930',
    storageBucket: 'ablnew-9f930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8a6aZ6RoWAmKrbuCuHqymc2dgcmJ2O5U',
    appId: '1:569573804437:ios:3038933612e5fd90880e9c',
    messagingSenderId: '569573804437',
    projectId: 'ablnew-9f930',
    storageBucket: 'ablnew-9f930.firebasestorage.app',
    iosBundleId: 'com.example.thriveers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8a6aZ6RoWAmKrbuCuHqymc2dgcmJ2O5U',
    appId: '1:569573804437:ios:3038933612e5fd90880e9c',
    messagingSenderId: '569573804437',
    projectId: 'ablnew-9f930',
    storageBucket: 'ablnew-9f930.firebasestorage.app',
    iosBundleId: 'com.example.thriveers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDleVP1qj0BFeWnNGiTtF3Jz_FhMUC3Gtw',
    appId: '1:569573804437:web:7abecda09f382b38880e9c',
    messagingSenderId: '569573804437',
    projectId: 'ablnew-9f930',
    authDomain: 'ablnew-9f930.firebaseapp.com',
    storageBucket: 'ablnew-9f930.firebasestorage.app',
  );
}
